'use strict';
const express = require('express');
const c = require('../../controllers/platformAdmin/platformAnnouncementController');
const auth = require('../../middleware/platformAdmin/authenticatePlatformAdmin');
const mfa = require('../../middleware/platformAdmin/requireMfa');
const pwd = require('../../middleware/platformAdmin/requireMustChangePassword');
const perm = require('../../middleware/platformAdmin/requirePlatformPermission');
const { PLATFORM_PERMISSIONS: P } = require('../../config/platformPermissions');
const router = express.Router(); const chain = [auth, mfa, pwd];
router.get('/', ...chain, perm(P.ANNOUNCEMENTS_MANAGE), c.list);
router.get('/:id', ...chain, perm(P.ANNOUNCEMENTS_MANAGE), c.get);
router.post('/', ...chain, perm(P.ANNOUNCEMENTS_MANAGE), c.create);
router.patch('/:id', ...chain, perm(P.ANNOUNCEMENTS_MANAGE), c.update);
router.post('/:id/publish', ...chain, perm(P.ANNOUNCEMENTS_MANAGE), c.publish);
router.post('/:id/schedule', ...chain, perm(P.ANNOUNCEMENTS_MANAGE), c.schedule);
router.post('/:id/archive', ...chain, perm(P.ANNOUNCEMENTS_MANAGE), c.archive);
module.exports = router;
