'use strict';
const express = require('express');
const c = require('../../controllers/platformAdmin/platformFeatureFlagController');
const auth = require('../../middleware/platformAdmin/authenticatePlatformAdmin');
const mfa = require('../../middleware/platformAdmin/requireMfa');
const pwd = require('../../middleware/platformAdmin/requireMustChangePassword');
const perm = require('../../middleware/platformAdmin/requirePlatformPermission');
const reauth = require('../../middleware/platformAdmin/requireRecentReauthentication');
const { PLATFORM_PERMISSIONS: P } = require('../../config/platformPermissions');
const router = express.Router();
const chain = [auth, mfa, pwd];
router.get('/', ...chain, perm(P.FEATURE_FLAGS_MANAGE), c.list);
router.get('/evaluate/:key', ...chain, perm(P.FEATURE_FLAGS_MANAGE), c.evaluate);
router.get('/:id/history', ...chain, perm(P.FEATURE_FLAGS_MANAGE), c.history);
router.get('/:id', ...chain, perm(P.FEATURE_FLAGS_MANAGE), c.get);
router.post('/', ...chain, perm(P.FEATURE_FLAGS_MANAGE), c.create);
router.patch('/:id', ...chain, perm(P.FEATURE_FLAGS_MANAGE), c.update);
router.delete('/:id', ...chain, reauth(15), perm(P.FEATURE_FLAGS_MANAGE), c.remove);
module.exports = router;
