import { useEffect, useState } from 'react'
import { Download, FileSpreadsheet, RefreshCw } from 'lucide-react'
import platformApi, { platformEndpoints } from '../lib/platformApi'

const TYPES = [
  ['COMMUNITIES', 'Communities'], ['USERS', 'Users'], ['AUDIT_LOGS', 'Audit logs'], ['SUPPORT_TICKETS', 'Support tickets'], ['FINANCIAL_AGGREGATE', 'Aggregate financials'],
]

export default function PlatformExports() {
  const [rows, setRows] = useState([]); const [type, setType] = useState('COMMUNITIES'); const [format, setFormat] = useState('CSV'); const [busy, setBusy] = useState(false)
  async function load() { const { data } = await platformApi.get(platformEndpoints.exports()); setRows(data.data || []) }
  useEffect(() => { load(); const id = setInterval(load, 5000); return () => clearInterval(id) }, [])
  async function create() { setBusy(true); try { await platformApi.post(platformEndpoints.exports(), { type, format, filters: {} }); await load() } finally { setBusy(false) } }
  async function download(job) { const response = await platformApi.get(platformEndpoints.exportDownload(job.id), { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const a = document.createElement('a'); a.href = url; a.download = job.fileName || 'export'; a.click(); URL.revokeObjectURL(url) }
  return <div className="space-y-5"><div><h1 className="text-2xl font-semibold text-white">Data Export</h1><p className="text-sm text-ink-400 mt-1">Exports are queued and generated outside the request lifecycle. Passwords, MFA secrets, tokens, and API keys are excluded.</p></div><div className="rounded-xl border border-ink-700 bg-ink-900 p-5"><div className="grid gap-4 sm:grid-cols-3"><label><span className="label">Dataset</span><select className="input" value={type} onChange={e=>setType(e.target.value)}>{TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label><span className="label">Format</span><select className="input" value={format} onChange={e=>setFormat(e.target.value)}><option>CSV</option><option>XLSX</option><option>JSON</option></select></label><div className="flex items-end"><button onClick={create} disabled={busy} className="btn-primary w-full inline-flex items-center justify-center gap-2"><FileSpreadsheet className="w-4 h-4"/>{busy?'Queueing…':'Queue export'}</button></div></div></div><div className="flex items-center justify-between"><div className="font-semibold text-white">Your export jobs</div><button onClick={load} className="btn-secondary inline-flex items-center gap-2"><RefreshCw className="w-4 h-4"/>Refresh</button></div><div className="rounded-xl border border-ink-700 bg-ink-900 overflow-hidden"><table className="min-w-full text-sm"><thead className="bg-ink-800/70 text-ink-400 text-left"><tr><th className="p-3">Job</th><th className="p-3">Format</th><th className="p-3">Status</th><th className="p-3">Created</th><th className="p-3 text-right">Action</th></tr></thead><tbody>{rows.map(j=><tr key={j.id} className="border-t border-ink-800"><td className="p-3"><div className="font-medium text-white">{j.type.replaceAll('_',' ')}</div><div className="text-[11px] text-ink-500 font-mono">{j.id}</div>{j.errorMessage&&<div className="text-xs text-red-300 mt-1">{j.errorMessage}</div>}</td><td className="p-3 text-ink-300">{j.format}</td><td className="p-3"><span className={`badge ${j.status==='COMPLETED'?'badge-success':j.status==='FAILED'?'badge-danger':'badge-neutral'}`}>{j.status}</span></td><td className="p-3 text-ink-400">{new Date(j.createdAt).toLocaleString()}</td><td className="p-3 text-right">{j.status==='COMPLETED'&&<button onClick={()=>download(j)} className="btn-secondary inline-flex items-center gap-2"><Download className="w-4 h-4"/>Download</button>}</td></tr>)}{!rows.length&&<tr><td colSpan="5" className="p-8 text-center text-ink-500">No export jobs yet.</td></tr>}</tbody></table></div></div>
}
